name: Continuous Integration and Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Configure ssh connection
          shell: bash
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_KNOWN_HOST: ${{ secrets.SSH_KNOWN_HOSTS }}
            DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
            DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
            PM2_CMD: ${{ vars.PM2_CMD }}
          run: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
            eval $(ssh-agent -s)
            echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
            echo "$DEPLOY_USER@$DEPLOY_HOST"
            echo "export PM2_CMD=$PM2_CMD" > env.remote
            scp env.remote $DEPLOY_USER@$DEPLOY_HOST:/tmp
            ssh $DEPLOY_USER@$DEPLOY_HOST 'cd /home/deploy/tst/dot.files; git pull'
            ssh $DEPLOY_USER@$DEPLOY_HOST 'source /tmp/env.remote; $PM2_CMD status'